trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYTHON_VERSION: '3.8'

stages:
- stage: Test
  jobs:
  - job: RunPyTests
    displayName: 'Run PyTests'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - task: AzureRmEndpoint@1  # Added step for service connection
      displayName: 'Authenticate with Azure'
      inputs:
        azureSubscriptionConnection: 'my-azure-service-connection'
        serviceEndpointName: '$(System.DefaultWorkingDirectory)'

    - script: |  # Modify your script to use credentials if needed
        endpoint = os.environ.get('AZURE_RM_ENDPOINT_NAME')

        pytest pytests.py
      displayName: 'Run PyTests'
