trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYTHON_VERSION: '3.8'

stages:
- stage: Test
  jobs:
  - job: RunPyTests
    displayName: 'Run PyTests'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Run your Azure CLI commands here if needed
          az account show
      displayName: 'Azure CLI operation'

    - script: |
        pytest tests/
      displayName: 'Run PyTests'
